### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by sxrzme** [k0rnh0li0/onlyfans-dl#118]
Traceback (most recent call last):, Estimated Time left: 0:00:00, Estimated finish time: 15:24:19
  File "C:\Users\Administrator\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 321, in <module>
    cur_count = download_posts(1, photo_posts, False)
  File "C:\Users\Administrator\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 222, in download_posts
    if not post["canViewMedia"]:
KeyError: 'canViewMedia'

**Comment by OmegaTangent** [comment]
I'm also getting this error, it also varies with how much it downloads before the error cancels progress

**Comment by Th3K1n91** [comment]
#109
