### ISSUE TITLE
any help here

### ISSUE THREAD

**Issue by sgaurav510** [k0rnh0li0/onlyfans-dl#157]
C:\Users\sgaur\Downloads\onlyfans-dl-master\onlyfans-dl-master>python onlyfans-dl.py

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ I AM THE GREAT KORNHOLIO ~
~  ARE U THREATENING ME??  ~
~                          ~
~    COOMERS GUNNA COOM    ~
~    HACKERS GUNNA HACK    ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):
  File "C:\Users\sgaur\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 345, in <module>
    API_HEADER = create_auth()
  File "C:\Users\sgaur\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 51, in create_auth
    ljson = json.load(f)
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 131 (char 132)

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
