### ISSUE TITLE
How do I use the fansly downloader?

### ISSUE THREAD

**Issue by Pwnager12345** [k0rnh0li0/onlyfans-dl#182]
Whenever I try to use the Fansly side of the downloader I get this error:
```
AttributeError: 'error_details' object has no attribute 'following'
```

Here is the full error report: 
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109d11810>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109d11840>
Traceback (most recent call last):
  File "/Users/ethanchong/Desktop/OnlyFans/start_ofd.py", line 108, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/ethanchong/Desktop/OnlyFans/start_ofd.py", line 93, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/ethanchong/Desktop/OnlyFans/datascraper/main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users/ethanchong/Desktop/OnlyFans/modules/fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "/Users/ethanchong/Desktop/OnlyFans/modules/fansly.py", line 1264, in manage_subscriptions
    results2 = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "/Users/ethanchong/Desktop/OnlyFans/apis/fansly/classes/create_auth.py", line 315, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "/Users/ethanchong/Desktop/OnlyFans/apis/fansly/classes/create_auth.py", line 305, in multi
    valid_subscriptions.following
AttributeError: 'error_details' object has no attribute 'following'
```

Can anyone help me?

P.S. The Onlyfans side works perfectly fine

**Comment by jordon31** [comment]
https://github.com/jordon31/OF-SCR

try my updated script
