### ISSUE TITLE
Expected string or bytes-like object error

### ISSUE THREAD

**Issue by petecodes123** [k0rnh0li0/onlyfans-dl#253]
Getting the below error

Saving profile info...
Downloading avatar...
Downloading header...
Finding photos... Found 753 photos.
Finding videos... Found 514 videos.
Finding archived content... Found 1 archived posts.
Found 1268 posts. Downloading media...
Traceback (most recent call last):Estimated Time left: 1:09:35, Estimated finish time: 23:12:46
  File "C:\Users\PeteAdmin\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 427, in <module>
    cur_count = download_posts(1, photo_posts, False)
  File "C:\Users\PeteAdmin\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 281, in download_posts
    download_media(media, is_archived)
  File "C:\Users\PeteAdmin\Downloads\onlyfans-dl-master\onlyfans-dl-master\onlyfans-dl.py", line 222, in download_media
    ext = re.findall('\.\w+\?', source)
  File "C:\Users\PeteAdmin\AppData\Local\Programs\Python\Python310\lib\re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

**Comment by Kempeter** [comment]
Fixed here: #252
